### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by QuantumExecute**
German translation made by CoolTom: https://cooltom.itch.io/helltaker-deutsche-uebersetzung

I´ve already asked for permssions but he hasn´t replied yet. I dont think there will be any problems.

### CODE REVIEW

**Comment by QuantumExecute** [comment]
Hey @D3fau4 

I have edited the original translation from CoolTom. It´s now better than the original.
Please feel free to add this to the switch port.

And thanks for the hard work.

**Comment by D3fau4** [comment]
thanks but i won't be able to add it and make a new build until thursday.

**Comment by QuantumExecute** [comment]
@D3fau4

No problem, take your time.

**Comment by D3fau4** [comment]
asd
done

**Comment by QuantumExecute** [comment]
Thank you. I will test it later.

**Comment by QuantumExecute** [comment]
@D3fau4

Thanks again for the update. I've installed the new version but it's in english. Do I have to change something in the settings?

**Comment by D3fau4** [comment]
I really choose the language based on the language of the console.

**Comment by QuantumExecute** [comment]
The language and region settings from my console is german. That's strange...

**Pull request merged**
