### PR TITLE
Add thai translation

### PR DESCRIPTION
**Pull request by nekopaldee**
I aware it may have problem with text displaying.
I've added glyph on the font to fix this problem but I can't remember which font does it use to display dialogue, so I uploaded both font in to this pull request.
Sorry for your inconvenience.

My repository of the translation: https://github.com/nekopaldee/helltaker_thai_localization

### CODE REVIEW

**Comment by D3fau4** [comment]
Do I need to add a new font?

**Comment by nekopaldee** [comment]
You can replace the font with the one that used in the game.
But if you want to add as a new font I can fix the font and sent it to you.

**Comment by D3fau4** [comment]
What differences are there between the original and yours?

**Comment by nekopaldee** [comment]
The original one don't have Thai character glyphs, so I added into it.

**Comment by D3fau4** [comment]
Okay thanks, it will take a few weeks to add it. I'm away from home and I don't have a computer to work.

**Pull request merged**
